In [1]:
print('meow, meow, meow')

meow, meow, meow


In [ ]:
import numpy as np

lg_arr = np.zeros((6,6))
my_arr = np.array([ [1,2], [1,2]])
new_arr = lg_arr.copy()

print(np.shape(lg_arr)[0])
print(np.shape(my_arr)[0])
N = np.shape(lg_arr)[0]//np.shape(my_arr)[0]

new_arr[:N,:N] = 2
new_arr[N:,N:] = 4
new_arr[N:2*N,:N] = 3
new_arr[:N,N:2*N] = 1

# print(my_arr)
# print(lg_arr)
print(new_arr)

N = np.shape(U)[0]//np.shape(BLOS)[0]
N_BLOS = np.zeros(np.shape(U))

N_BLOS[:N,:N] = 2
N_BLOS[N:,N:] = 4
N_BLOS[N:2*N,:N] = 3
N_BLOS[:N,N:2*N] = 1


6
2
[[2. 2. 2. 1. 1. 1.]
 [2. 2. 2. 1. 1. 1.]
 [2. 2. 2. 1. 1. 1.]
 [3. 3. 3. 4. 4. 4.]
 [3. 3. 3. 4. 4. 4.]
 [3. 3. 3. 4. 4. 4.]]


In [42]:
lg_arr = np.zeros((6,6))
sm_arr = np.array([[1,1,1],[2,2,2],[3,3,3]])
new_arr = lg_arr.copy()

for i in range(np.shape(lg_arr)[0]):
    for j in range(np.shape(lg_arr)[1]):
        ifrac = i/np.shape(lg_arr)[0]
        jfrac = j/np.shape(lg_arr)[1]
        iblos = int(ifrac*np.shape(sm_arr)[0])
        jblos = int(jfrac*np.shape(sm_arr)[1])
        new_arr[i,j] = sm_arr[iblos,jblos]

In [43]:
print(sm_arr)
print(lg_arr)
print(new_arr)

[[1 1 1]
 [2 2 2]
 [3 3 3]]
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2.]
 [3. 3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3. 3.]]
